- name: SSH to EC2 and deploy
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.SSH_KEY }}
    script: |
      docker pull your-dockerhub/flask-devops-app:latest
      docker stop app || true && docker rm app || true
      docker run -d -p 5000:5000 --name app your-dockerhub/flask-devops-app:latest
